language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run -m --source=tests/ --branch unittest tests.test_report_processer
after_success: coveralls
