language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install -r requirements-dev.txt
script:
  - flake8 --exclude=./tests/* --exit-zero
  - coverage run -m --source=csv_report_processer --branch unittest
after_success: coveralls
